package com.example.scheduler.repositories;

import com.example.scheduler.entities.RemindersEntity;
import org.springframework.data.repository.CrudRepository;

import java.util.List;

/**
 * Special Interface for a CrudRepository that works on reminder entities
 * Note: Implementations for this interface are automatically
 * generated by the Spring Framework. @Annotations  or method names
 * should be used for changing the implementation.
 */
public interface ReminderRepository extends CrudRepository<RemindersEntity, Long> {

    List<RemindersEntity> findByOrderByDateAsc();
    RemindersEntity findByEventId(Long eventId);

}
